### ISSUE TITLE
Please update asdf-linguist for ASDF3

### ISSUE THREAD

**Issue by fare** [eudoxia0/asdf-linguist#1]
Your run function is somewhat buggy: run-shell-command already does a format. Thus, you're going to lose badly if there's a ~ in your command. More generally, run-shell-command is a very bad interface. I recommend you use run-program instead, or inferior-shell if you're going to do complex pipes.

A lot of the complexity in your .asd file can go away, too. No need for you the package frobbing. And to include some file's contents, use #.(uiop:read-file-string (subpathname *load-pathname* "README")) or some such.

**Comment by EuAndreh** [comment]
Is there any topic pending from this issue?

**Comment by fare** [comment]
Using *load-pathname* is incorrect, in case someone uses a symlink farm (or worse, shudder, "logical" pathnames). You should use *load-truename*, or better, use (asdf:system-relative-pathname ...)

I recommend using (defsystem ...) instead of (asdf:defsystem ...)

**Comment by fare** [comment]
run-command is a buggy interface. Formatting a command is a good way to hell, what with improperly escaped characters, etc. You should use inferior-shell:run directly, and not try to interpolate a command this way.

**Comment by EuAndreh** [comment]
I believe I changed from `asdf:run-shell-command` to `inferior-shell:run` in PR #5.

**Comment by EuAndreh** [comment]
I'll open a PR with `(asdf:system-relative-pathname ...)`

**Comment by fare** [comment]
Yes, but you're kind of simulating the broken API of run-shell-command on top of inferior-shell, which is better than run-shell-command (which was broken in other ways, too), but still not ideal.

**Comment by EuAndreh** [comment]
You mean changing from a single string to a list of strings?

**Comment by fare** [comment]
A list of strings would be better indeed. Or just let the component call inferior-shell:run by itself.

**Comment by fare** [comment]
Also, unlike `uiop:run-program`, `inferior-shell:run` (which btw accepts `:show t`) will DTRT with pathnames, and will do string interpolation, etc.

**Comment by EuAndreh** [comment]
When changing to `(asdf:system-relative-pathname :asdf-linguist "README.md")`, I get this new error:
````lisp
[Condition of type ASDF/FIND-SYSTEM:LOAD-SYSTEM-DEFINITION-ERROR]
```

It tries to find the `:asdf-linguist` system definition, and when it starts to read and load the `asdf-linguist.asd` file, it finds the same `(asdf:system-relative-pathname ...)` form (with the `#.` read-macro) and runs again and again, recursively.

Should I use `*load-truename*`, instead?

**Comment by fare** [comment]
Yeah, there's a circular definition problem in this case when using system-relative-pathname, so falling back to using a subpathname of *load-truename* is a good idea.

**Comment by EuAndreh** [comment]
Am I going the [right direction](https://github.com/eudoxia0/asdf-linguist/pull/6/files#diff-8a891105f889c730ad56bbcc421514a4R38)?

**Comment by fare** [comment]
What about instead (deffoo (name (&key ...) &body ...) and let the users specify arbitrary forms in the body that evaluate to the command, with properly bound variables for input and output (with or without defaults)?

**Comment by EuAndreh** [comment]
Isn't that what is already happening with [`define-component`](https://github.com/EuAndreh/asdf-linguist/blob/bb970fc5f53af06e4b10555194b61ab6a6ab4292/src/www/js.lisp#L22) (instead of `define-shell-component`)?

**Comment by fare** [comment]
Transforming define-shell-component into a trivial wrapper around define-component looks like a good idea indeed.
